---
# tasks file for nginx

- name: Install EPEL
  shell: sudo amazon-linux-extras install epel -y

- name: Enable EPEL
  shell: sudo yum-config-manager --enable epel

- name: Install nginx
  package:
    name: nginx
    update_cache: true
    state: latest
   
- name: Restart nginx
  service:
    name: nginx
    state: restarted

