## Include_tasks are dynamic

---

 - hosts: all
   gather_facts: false
   tasks:
     - name: Play 1 - Task 1
       debug:
         msg: Play 1 - Task 1
  
     - include_tasks: 1.play1_task2.yml

...
